# Travis CI configuration
language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7

install:
  - pip install -r requirements.txt

# command to run tests
script: pytest --doctest-modules



CODECOV_TOKEN="c4689aff-f82e-45b6-934c-f9cec76098f1"
